/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import clases.Clientes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno L2 Maq-14
 */
public class Clientes2 extends javax.swing.JInternalFrame {
     

    /**
     * Creates new form Clientes2
     */
    public Clientes2() {
        initComponents();
           CargarTabla();
    }
    
     Clientes objUser = new Clientes();
    int id;
    String Nombre;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnEnviar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultar = new javax.swing.JTable();

        jPopupMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPopupMenu1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        mnEnviar.setText("Enviar_Datos");
        mnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEnviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnEnviar);

        setClosable(true);

        jLabel1.setText("  Buscar_Cliente");

        tbConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono"
            }
        ));
        tbConsultar.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbConsultar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPopupMenu1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPopupMenu1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1AncestorAdded

    private void mnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEnviarActionPerformed
        // TODO add your handling code here:
      String nom="", apellido="";
      int seleccion = tbConsultar.getSelectedRow();
      if(seleccion== -1)
      {
         JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");
         
      }
      else
      {
          
          nom = (String) tbConsultar.getValueAt(seleccion,1);
          apellido = (String) tbConsultar.getValueAt(seleccion,2);
          frmVentas.txtCliente.setText(nom+" "+apellido);
                  
                  
                  
          //frmVentas.txtcod.setText(cod);
          //.txtCliente.setText(nom+" "+ape);  
                  
           this.dispose();
      }
        
    }//GEN-LAST:event_mnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnEnviar;
    private javax.swing.JTable tbConsultar;
    // End of variables declaration//GEN-END:variables

    private void CargarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tbConsultar.getModel();
        
        modelo.setRowCount(0);
        
        try{
            ResultSet consultar = objUser.consultar();
            
            while(consultar.next()){
                Vector v =  new Vector();
                v.add(consultar.getInt(1));
                v.add(consultar.getString(2));
                v.add(consultar.getString(3));
                v.add(consultar.getString(4));
                
                
                modelo.addRow(v);
                tbConsultar.setModel(modelo);
            }
        }catch (SQLException e){
            System.out.println(e);
        }
    }

    private int _1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 }



